### ISSUE TITLE
View All Posts (3)

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-58/rare-client-demolition-buccaneers#24]
Given the user clicks on the "Posts" link in the navbar
When they are directed to the /posts page
Then they should see a list of all posts, with the post title, author name, and category
And the posts should be ordered by the date they were added, most recent first

**Comment by Russ716** [comment]
http://localhost:3000/posts meets these criteria

**Comment by Russ716** [comment]
Now matches the wireframe
